### ISSUE TITLE
 Questions about the data set

### ISSUE THREAD

**Issue by hmppt** [BHui97/PLeak#1]
I briefly looked at the contents of the Financial data set and found that the prompts are not system prompts. Does this mean that the use of any data set is allowed?

Also, is the initialization of adv query random? I see that the optimized adv query in your example is semantic, but if you randomly initialize an adv query and optimize it, it will be difficult to get a semantic query.

**Comment by BHui97** [comment]
You can try any data as system prompt to see the results. For the second question, it depends on the model used. If the model is aligned by human feedback, it will become more semantic.
