### ISSUE TITLE
Ask about the  transferability

### ISSUE THREAD

**Issue by mengtong0110** [BHui97/PLeak#2]
Hi @BHui97, great job on the work!

I have a question regarding the experiments on transferability. It appears that the optimization of the adversarial query is performed on tokenized data. However, users submit the adversarial query in string format, which is then tokenized by the LLMs. I’ve noticed a discrepancy between these two token sequences, and the attack success rate differs. Could there be an issue with the version of the uploaded code in the GitHub repository?

How could I solve it? Thanks~

**Comment by renhl717445** [comment]
When running python main.py Financial 12 gptj gptj 16 or other models, errors are reported: File "/home/LLM/PLeak/Attack.py", line 103, in make_target_chat
target = self.tokenizer.apply_chat_template(target)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1803, in apply_chat_template
chat_template = self. get_chat_template(chat_template, tools)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/conda/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1967, in get_chat_template raise ValueError( ValueError: Cannot use chat template functions because tokenizer. chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer. chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating , how did you solve it?

**Comment by BHui97** [comment]
In the function of computing_loss, it should be make_target instead make_target_chat. I have updated the code to the latest version. Sorry for the confusion.

**Comment by renhl717445** [comment]
Thanks for your reply, but when I run the new code, there are still some inexplicable problems. In python main.py Financial 12 opt opt ​​16, I print the loss in computer_loss and it shows as follows. Is this normal?

1，python main.py Financial 12 opt opt ​​16
 init_triggers: supportersLooks crotchadiatorMedsuff675 layouts CotPosition unconstitutional purely
-----------loss------------:  tensor(0., device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(3.0994e-06, device='cuda:3', dtype=torch.float16,
       grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(683.5000, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16, grad_fn=<DivBackward0>)
current loss:nan, triggers: supportersLooks crotchadiatorMedsuff675 layouts CotPosition unconstitutional purely
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(0.1054, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)
-----------loss------------:  tensor(nan, device='cuda:3', dtype=torch.float16)

2，python main.py Financial 12 llama llama 16
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:11<00:00,  5.96s/it]
init_triggers:pngResolverkor eredet botbibliothek centralehus questa allenyard Development
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [4,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [5,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [6,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [7,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [8,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [9,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [10,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [11,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [12,0,0] Assertion `t >= 0 && t < n_classes` failed.
../aten/src/ATen/native/cuda/Loss.cu:250: nll_loss_forward_reduce_cuda_kernel_2d: block: [0,0,0], thread: [13,0,0] Assertion `t >= 0 && t < n_classes` failed.
...
Traceback (most recent call last):
  File "/home/LLM/PLeak/main.py", line 30, in <module>
    attack.replace_triggers(trainset)
  File "/home/LLM/PLeak/Attack.py", line 163, in replace_triggers
    best_loss = self.compute_loss(target_texts, self.trigger_tokens, idx_loss, require_grad=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/LLM/PLeak/Attack.py", line 136, in compute_loss
    loss = self.model(lm_input, labels=label)[0]/len(target_texts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1214, in forward
    loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **loss_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/loss/loss_utils.py", line 46, in ForCausalLMLoss
    loss = fixed_cross_entropy(shift_logits, shift_labels, num_items_in_batch, ignore_index, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/loss/loss_utils.py", line 26, in fixed_cross_entropy
    loss = nn.functional.cross_entropy(source, target, ignore_index=ignore_index, reduction=reduction)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/functional.py", line 3479, in cross_entropy
    return torch._C._nn.cross_entropy_loss(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. 
How can I solve this?

**Comment by BHui97** [comment]
From my side, I don't have such issues. I guess it is raised from environment.

**Comment by renhl717445** [comment]
It seems to be a mismatched label problem. Add a -100 to the make_target label
The class of. But it's not in the model's vocabulary. But I'll replace -100 with padding_idx or eos_token
The same error was reported. In addition, the maximum value of the tag is 29955, but the value set in modelFactory is 32000. Is there anything else you need to change？
